### ISSUE TITLE
Implement a XmlXPathChoiceListProvider so that entries could be read from the pom.xml

### ISSUE THREAD

**Issue by mrumpf** [ikedam/extensible-choice-parameter#28]
Having a XmlXPathChoiceListProvider would allow to grab certain entries from an XML file.
In our case we want to grab all Maven provile ids because those profile ids are the name of the environments where you can deploy an artifact to.
The selected entry could later be passed to the Maven build by something like that "-P${profileId}"...

**Comment by amandel** [comment]
+1

Filename should be free could be any file - not only pom.xml, but I think that is intended.

**Comment by mrumpf** [comment]
Yes, the filename should be relative to the job's workspace

**Comment by mrumpf** [comment]
Use the official Jenkins JIRA instead of Github issues: https://issues.jenkins-ci.org/browse/JENKINS-27528
