### ISSUE TITLE
onBuildTriggeredWithValue update value

### ISSUE THREAD

**Issue by phreakadelle** [ikedam/extensible-choice-parameter#36]
Hi Ikedam,
i've created an own ChoiceListProvider which provides values from a Nexus/Repository:
- https://github.com/jenkinsci/maven-artifact-choicelistprovider-plugin

Currently i am trying to solve the problem, that the URLs displayed in the Box are too long. So i would like to display just the ArtifactIds/GroupIds or at least something shorter then the full URL. But before the build is triggered, i need to update the value to the full URL again.
- https://github.com/phreakadelle/maven-artifact-choicelistprovider-plugin/issues/3

In your plugin the method "onBuildTriggeredWithValue" exists but i dont know how to update the current build with a new value. I would very appreciate your help on that.

Regards
Stephan

**Comment by ikedam** [comment]
Please use JIRA for issue tracking.
Extencible-choice doesn't have a feature for that purpose.
It should be a new feature supporting key-value choices.
https://issues.jenkins-ci.org/browse/JENKINS-22317

**Comment by phreakadelle** [comment]
Hi Ikedam, thanks for your reply. As i can see i've already voted for this issue in May 2016 ;-) 
Would be really nice to have this feature.  Thanks in advance.

**Comment by ikedam** [comment]
Moved to https://issues.jenkins-ci.org/browse/JENKINS-22317
